<?php
function displaySmiley($text,$smileyDir = "images/smiley/")
{
	$verify = array(":)",":-)",":D",":d",":-D",":-d",":(",":-(",":'(",":((",":-o",":-O",":o",":O","x-(","x(","X-(","X(",":p",":P",":-p",":-P",":-|","<3");
	$images = array("<img src=\"".$smileyDir."big-smile-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."big-smile-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."haha-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."haha-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."haha-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."haha-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."unhappy-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."unhappy-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."cry-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."cry-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."amazing-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."amazing-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."amazing-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."amazing-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."anger-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."anger-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."anger-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."anger-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."grimace-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."grimace-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."grimace-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."grimace-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."shame-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />","<img src=\"".$smileyDir."black-heart-icon.png\" alt=\"\" border=\"0\" class=\"smileyimage\" />");
	$returnstr = str_replace($verify,$images,$text);
	return $returnstr;
}
?>
